import os
from dotenv import load_dotenv

load_dotenv()

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
TWILIO_ACCOUNT_SID = os.getenv("TWILIO_ACCOUNT_SID")
TWILIO_AUTH_TOKEN = os.getenv("TWILIO_AUTH_TOKEN")
TWILIO_PHONE_NUMBER = os.getenv("TWILIO_PHONE_NUMBER")
SENDGRID_API_KEY = os.getenv("SENDGRID_API_KEY")
SENDGRID_FROM_EMAIL = os.getenv("SENDGRID_FROM_EMAIL")
MARKETCHECK_API_KEY = os.getenv("MARKETCHECK_API_KEY")
AUTODEV_API_KEY = os.getenv("AUTODEV_API_KEY")

LLM_MODEL = "gpt-4o-mini"
MAX_RESULTS = 20
MAX_REVISION_CYCLES = 2
